import type {
  DeliveryDriver,
  DriverDelivery,
  DriverDocument,
  DriverReview,
  GrowthPoint,
  EarningsPoint,
} from '@/features/delivery-drivers/types'

function avatar(seed: string) {
  return `https://i.pravatar.cc/128?u=${encodeURIComponent(seed)}`
}

function reviewsFor(driverId: string, base: Omit<DriverReview, 'id'>[]): DriverReview[] {
  return base.map((r, i) => ({ ...r, id: `${driverId}-R-${i}` }))
}

export function deliveriesTemplate(driverId: string): DriverDelivery[] {
  const vendors = ['Spice Route Kitchen', 'Urban Bites', 'FreshMart Express', 'Cafe Noir', 'Thai Garden']
  const customers = ['Sara K.', 'James M.', 'Nadia R.', 'Omar H.', 'Priya S.', 'Leo T.']
  const rows: DriverDelivery[] = []
  for (let i = 0; i < 12; i++) {
    const day = Math.max(1, 20 - Math.floor(i / 2))
    let st: DriverDelivery['status'] = 'completed'
    if (i === 0) st = 'in_transit'
    else if (i % 9 === 0) st = 'cancelled'
    else if (i % 11 === 0) st = 'failed'
    rows.push({
      id: `D-${driverId}-${100 + i}`,
      customer: customers[i % customers.length],
      vendor: vendors[i % vendors.length],
      deliveryFee: 2.5 + (i % 5) * 0.75,
      distanceKm: 1.2 + (i % 7) * 0.6,
      status: st,
      completedAt:
        st === 'completed'
          ? `2026-05-${String(day).padStart(2, '0')} ${String(14 + (i % 4)).padStart(2, '0')}:${String((i * 7) % 60).padStart(2, '0')}:00`
          : null,
      date: `2026-05-${String(day).padStart(2, '0')}`,
    })
  }
  return rows
}

export function weekSeries(seed: number): EarningsPoint[] {
  return ['W1', 'W2', 'W3', 'W4'].map((label, i) => ({
    label,
    amount: Math.round(180 + seed * 17 + i * 42 + (i % 3) * 20),
  }))
}

export function monthSeries(seed: number): EarningsPoint[] {
  return ['Jan', 'Feb', 'Mar', 'Apr', 'May'].map((label, i) => ({
    label,
    amount: Math.round(1200 + seed * 40 + i * 180 + (i % 2) * 90),
  }))
}

export function growthSeries(seed: number): GrowthPoint[] {
  return ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((label, i) => ({
    label,
    count: Math.max(0, Math.round(4 + (seed % 5) + i * 0.8 + (i % 2) * 3)),
  }))
}

const pendingDocs = (id: string): DriverDocument[] => [
  {
    label: 'National ID (NID)',
    fileName: `${id}_nid_front.jpg`,
    uploadedAt: '2026-05-02 11:20',
    previewUrl: 'https://placehold.co/320x200/eadbc9/62371a?text=NID+Front',
  },
  {
    label: 'Driving License',
    fileName: `${id}_license.pdf`,
    uploadedAt: '2026-05-02 11:22',
    previewUrl: 'https://placehold.co/320x200/d8bb96/3d200e?text=License',
  },
  {
    label: 'Vehicle Registration',
    fileName: `${id}_vehicle_reg.jpg`,
    uploadedAt: '2026-05-02 11:25',
    previewUrl: 'https://placehold.co/320x200/c49b63/ffffff?text=Vehicle+Papers',
  },
  {
    label: 'Profile photo',
    fileName: `${id}_profile.png`,
    uploadedAt: '2026-05-02 11:30',
    previewUrl: avatar(`${id}-doc`),
  },
]

const sampleReviewTexts = [
  'Polite and fast — food arrived hot.',
  'Great communication at the gate.',
  'Careful with packaging, appreciated.',
  'Slight delay but driver apologized proactively.',
  'Excellent — followed delivery notes perfectly.',
]

export const DEMO_DRIVERS_SEED: DeliveryDriver[] = [
  {
    id: 'DRV-501',
    name: 'Karim Hassan',
    email: 'karim.hassan@mail.test',
    phone: '+880 1711 902244',
    country: 'Bangladesh',
    vehicleType: 'Motorcycle',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'delivering',
    rating: 4.8,
    ratingCount: 312,
    completedOrders: 1840,
    cancelledOrders: 42,
    totalEarnings: 48210.5,
    weeklyEarnings: 1288.4,
    joinDate: '2024-03-12',
    avgDeliveryMinutes: 22,
    avatarUrl: avatar('DRV-501'),
    completedToday: 14,
    reviews: reviewsFor('DRV-501', [
      {
        customerName: 'Ayesha Khan',
        customerAvatar: avatar('c-ayesha'),
        rating: 5,
        text: sampleReviewTexts[0],
        deliveryDate: '2026-05-03',
        orderId: 'O-99201',
      },
      {
        customerName: 'Rafiq M.',
        customerAvatar: avatar('c-rafiq'),
        rating: 4,
        text: sampleReviewTexts[2],
        deliveryDate: '2026-05-01',
        orderId: 'O-99112',
      },
    ]),
    deliveries: deliveriesTemplate('501'),
    weeklyEarningsSeries: weekSeries(3),
    monthlyEarningsSeries: monthSeries(5),
    deliveryGrowthSeries: growthSeries(11),
  },
  {
    id: 'DRV-502',
    name: 'Elena Vasquez',
    email: 'elena.v@rider.io',
    phone: '+971 50 441 2290',
    country: 'UAE',
    vehicleType: 'Car',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'online',
    rating: 4.9,
    ratingCount: 521,
    completedOrders: 2633,
    cancelledOrders: 31,
    totalEarnings: 91240.0,
    weeklyEarnings: 2102.75,
    joinDate: '2023-11-02',
    avgDeliveryMinutes: 28,
    avatarUrl: avatar('DRV-502'),
    completedToday: 9,
    reviews: reviewsFor('DRV-502', [
      {
        customerName: 'Mohammed Ali',
        customerAvatar: avatar('c-mali'),
        rating: 5,
        text: sampleReviewTexts[4],
        deliveryDate: '2026-05-03',
        orderId: 'O-99344',
      },
    ]),
    deliveries: deliveriesTemplate('502'),
    weeklyEarningsSeries: weekSeries(7),
    monthlyEarningsSeries: monthSeries(8),
    deliveryGrowthSeries: growthSeries(9),
  },
  {
    id: 'DRV-503',
    name: 'Tom Williams',
    email: 'tom.w@fleet.uk',
    phone: '+44 7700 900321',
    country: 'UK',
    vehicleType: 'Bicycle',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'idle',
    rating: 4.6,
    ratingCount: 198,
    completedOrders: 890,
    cancelledOrders: 18,
    totalEarnings: 22400.25,
    weeklyEarnings: 612.0,
    joinDate: '2025-01-18',
    avgDeliveryMinutes: 19,
    avatarUrl: avatar('DRV-503'),
    completedToday: 6,
    reviews: reviewsFor('DRV-503', [
      {
        customerName: 'Lucy P.',
        customerAvatar: avatar('c-lucy'),
        rating: 5,
        text: sampleReviewTexts[1],
        deliveryDate: '2026-04-30',
        orderId: 'O-98801',
      },
    ]),
    deliveries: deliveriesTemplate('503'),
    weeklyEarningsSeries: weekSeries(2),
    monthlyEarningsSeries: monthSeries(3),
    deliveryGrowthSeries: growthSeries(4),
  },
  {
    id: 'DRV-504',
    name: 'Jamal Uddin',
    email: 'jamal.u@pathao-style.test',
    phone: '+880 1812 334455',
    country: 'Bangladesh',
    vehicleType: 'Motorcycle',
    accountStatus: 'pending',
    verified: false,
    liveStatus: 'offline',
    rating: 0,
    ratingCount: 0,
    completedOrders: 0,
    cancelledOrders: 0,
    totalEarnings: 0,
    weeklyEarnings: 0,
    joinDate: '2026-05-03',
    avgDeliveryMinutes: 0,
    avatarUrl: avatar('DRV-504'),
    completedToday: 0,
    documents: pendingDocs('DRV-504'),
    reviews: [],
    deliveries: [],
    weeklyEarningsSeries: weekSeries(0).map((p) => ({ ...p, amount: 0 })),
    monthlyEarningsSeries: monthSeries(0).map((p) => ({ ...p, amount: 0 })),
    deliveryGrowthSeries: growthSeries(0).map((p) => ({ ...p, count: 0 })),
  },
  {
    id: 'DRV-505',
    name: 'Priya Natarajan',
    email: 'priya.n@wak.test',
    phone: '+65 9123 7788',
    country: 'Singapore',
    vehicleType: 'Motorcycle',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'offline',
    rating: 4.7,
    ratingCount: 640,
    completedOrders: 3102,
    cancelledOrders: 55,
    totalEarnings: 105500.9,
    weeklyEarnings: 2440.2,
    joinDate: '2023-06-20',
    avgDeliveryMinutes: 24,
    avatarUrl: avatar('DRV-505'),
    completedToday: 0,
    reviews: reviewsFor('DRV-505', [
      {
        customerName: 'Chen W.',
        customerAvatar: avatar('c-chen'),
        rating: 5,
        text: sampleReviewTexts[3],
        deliveryDate: '2026-05-02',
        orderId: 'O-99012',
      },
    ]),
    deliveries: deliveriesTemplate('505'),
    weeklyEarningsSeries: weekSeries(9),
    monthlyEarningsSeries: monthSeries(6),
    deliveryGrowthSeries: growthSeries(14),
  },
  {
    id: 'DRV-506',
    name: 'Marcus Lee',
    email: 'marcus.lee@rider.io',
    phone: '+1 415 555 0192',
    country: 'USA',
    vehicleType: 'Car',
    accountStatus: 'suspended',
    verified: true,
    liveStatus: 'offline',
    rating: 4.2,
    ratingCount: 88,
    completedOrders: 420,
    cancelledOrders: 64,
    totalEarnings: 12880.0,
    weeklyEarnings: 0,
    joinDate: '2024-09-05',
    avgDeliveryMinutes: 35,
    avatarUrl: avatar('DRV-506'),
    completedToday: 0,
    reviews: reviewsFor('DRV-506', [
      {
        customerName: 'Alex R.',
        customerAvatar: avatar('c-alex'),
        rating: 3,
        text: 'Late twice this week.',
        deliveryDate: '2026-04-28',
        orderId: 'O-98700',
      },
    ]),
    deliveries: deliveriesTemplate('506'),
    weeklyEarningsSeries: weekSeries(1),
    monthlyEarningsSeries: monthSeries(2),
    deliveryGrowthSeries: growthSeries(3),
  },
  {
    id: 'DRV-507',
    name: 'Sofia Andersson',
    email: 'sofia.a@nordic.test',
    phone: '+46 70 991 2211',
    country: 'Sweden',
    vehicleType: 'Bicycle',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'online',
    rating: 4.95,
    ratingCount: 412,
    completedOrders: 1520,
    cancelledOrders: 12,
    totalEarnings: 38990.5,
    weeklyEarnings: 920.4,
    joinDate: '2024-07-01',
    avgDeliveryMinutes: 17,
    avatarUrl: avatar('DRV-507'),
    completedToday: 11,
    reviews: reviewsFor('DRV-507', [
      {
        customerName: 'Erik L.',
        customerAvatar: avatar('c-erik'),
        rating: 5,
        text: sampleReviewTexts[0],
        deliveryDate: '2026-05-03',
        orderId: 'O-99301',
      },
    ]),
    deliveries: deliveriesTemplate('507'),
    weeklyEarningsSeries: weekSeries(6),
    monthlyEarningsSeries: monthSeries(7),
    deliveryGrowthSeries: growthSeries(8),
  },
  {
    id: 'DRV-508',
    name: 'Hassan Al Fayed',
    email: 'hassan.af@emirates.test',
    phone: '+971 52 881 0092',
    country: 'UAE',
    vehicleType: 'Van',
    accountStatus: 'pending',
    verified: false,
    liveStatus: 'offline',
    rating: 0,
    ratingCount: 0,
    completedOrders: 0,
    cancelledOrders: 0,
    totalEarnings: 0,
    weeklyEarnings: 0,
    joinDate: '2026-05-03',
    avgDeliveryMinutes: 0,
    avatarUrl: avatar('DRV-508'),
    completedToday: 0,
    documents: pendingDocs('DRV-508'),
    reviews: [],
    deliveries: [],
    weeklyEarningsSeries: weekSeries(0).map((p) => ({ ...p, amount: 0 })),
    monthlyEarningsSeries: monthSeries(0).map((p) => ({ ...p, amount: 0 })),
    deliveryGrowthSeries: growthSeries(0).map((p) => ({ ...p, count: 0 })),
  },
  {
    id: 'DRV-509',
    name: 'Nguyen Minh',
    email: 'minh.nguyen@vn.test',
    phone: '+84 91 223 4455',
    country: 'Vietnam',
    vehicleType: 'Motorcycle',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'delivering',
    rating: 4.5,
    ratingCount: 267,
    completedOrders: 1205,
    cancelledOrders: 28,
    totalEarnings: 30120.75,
    weeklyEarnings: 702.1,
    joinDate: '2024-11-11',
    avgDeliveryMinutes: 21,
    avatarUrl: avatar('DRV-509'),
    completedToday: 8,
    reviews: reviewsFor('DRV-509', [
      {
        customerName: 'Lan T.',
        customerAvatar: avatar('c-lan'),
        rating: 4,
        text: sampleReviewTexts[2],
        deliveryDate: '2026-05-02',
        orderId: 'O-99188',
      },
    ]),
    deliveries: deliveriesTemplate('509'),
    weeklyEarningsSeries: weekSeries(4),
    monthlyEarningsSeries: monthSeries(4),
    deliveryGrowthSeries: growthSeries(6),
  },
  {
    id: 'DRV-510',
    name: 'Amira Said',
    email: 'amira.said@cairo.test',
    phone: '+20 100 2211 8833',
    country: 'Egypt',
    vehicleType: 'Motorcycle',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'idle',
    rating: 4.7,
    ratingCount: 156,
    completedOrders: 702,
    cancelledOrders: 15,
    totalEarnings: 18840.0,
    weeklyEarnings: 410.25,
    joinDate: '2025-04-22',
    avgDeliveryMinutes: 26,
    avatarUrl: avatar('DRV-510'),
    completedToday: 5,
    reviews: reviewsFor('DRV-510', [
      {
        customerName: 'Youssef K.',
        customerAvatar: avatar('c-youssef'),
        rating: 5,
        text: sampleReviewTexts[4],
        deliveryDate: '2026-05-01',
        orderId: 'O-99044',
      },
    ]),
    deliveries: deliveriesTemplate('510'),
    weeklyEarningsSeries: weekSeries(5),
    monthlyEarningsSeries: monthSeries(5),
    deliveryGrowthSeries: growthSeries(7),
  },
  {
    id: 'DRV-511',
    name: 'Daniel Okafor',
    email: 'daniel.okafor@lagos.test',
    phone: '+234 803 441 2299',
    country: 'Nigeria',
    vehicleType: 'Motorcycle',
    accountStatus: 'blocked',
    verified: true,
    liveStatus: 'offline',
    rating: 3.1,
    ratingCount: 44,
    completedOrders: 210,
    cancelledOrders: 48,
    totalEarnings: 4100.0,
    weeklyEarnings: 0,
    joinDate: '2025-08-14',
    avgDeliveryMinutes: 48,
    avatarUrl: avatar('DRV-511'),
    completedToday: 0,
    reviews: reviewsFor('DRV-511', [
      {
        customerName: 'Chioma O.',
        customerAvatar: avatar('c-chioma'),
        rating: 2,
        text: 'Order marked delivered but never received.',
        deliveryDate: '2026-04-10',
        orderId: 'O-98001',
      },
    ]),
    deliveries: deliveriesTemplate('511'),
    weeklyEarningsSeries: weekSeries(1),
    monthlyEarningsSeries: monthSeries(1),
    deliveryGrowthSeries: growthSeries(2),
  },
  {
    id: 'DRV-512',
    name: 'Li Wei',
    email: 'li.wei@my.test',
    phone: '+60 12 778 9901',
    country: 'Malaysia',
    vehicleType: 'Bicycle',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'online',
    rating: 4.4,
    ratingCount: 92,
    completedOrders: 445,
    cancelledOrders: 9,
    totalEarnings: 11220.5,
    weeklyEarnings: 298.0,
    joinDate: '2025-10-02',
    avgDeliveryMinutes: 18,
    avatarUrl: avatar('DRV-512'),
    completedToday: 7,
    reviews: reviewsFor('DRV-512', [
      {
        customerName: 'Hannah T.',
        customerAvatar: avatar('c-hannah'),
        rating: 4,
        text: sampleReviewTexts[1],
        deliveryDate: '2026-05-03',
        orderId: 'O-99288',
      },
    ]),
    deliveries: deliveriesTemplate('512'),
    weeklyEarningsSeries: weekSeries(8),
    monthlyEarningsSeries: monthSeries(9),
    deliveryGrowthSeries: growthSeries(10),
  },
  {
    id: 'DRV-513',
    name: 'Olivia Brooks',
    email: 'olivia.brooks@us.test',
    phone: '+1 212 555 8844',
    country: 'USA',
    vehicleType: 'Car',
    accountStatus: 'pending',
    verified: false,
    liveStatus: 'offline',
    rating: 0,
    ratingCount: 0,
    completedOrders: 0,
    cancelledOrders: 0,
    totalEarnings: 0,
    weeklyEarnings: 0,
    joinDate: '2026-05-02',
    avgDeliveryMinutes: 0,
    avatarUrl: avatar('DRV-513'),
    completedToday: 0,
    documents: pendingDocs('DRV-513'),
    reviews: [],
    deliveries: [],
    weeklyEarningsSeries: weekSeries(0).map((p) => ({ ...p, amount: 0 })),
    monthlyEarningsSeries: monthSeries(0).map((p) => ({ ...p, amount: 0 })),
    deliveryGrowthSeries: growthSeries(0).map((p) => ({ ...p, count: 0 })),
  },
  {
    id: 'DRV-514',
    name: 'Raj Patel',
    email: 'raj.patel@in.test',
    phone: '+91 98765 43210',
    country: 'India',
    vehicleType: 'Motorcycle',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'offline',
    rating: 4.3,
    ratingCount: 1203,
    completedOrders: 4021,
    cancelledOrders: 120,
    totalEarnings: 98200.0,
    weeklyEarnings: 1980.5,
    joinDate: '2023-02-14',
    avgDeliveryMinutes: 31,
    avatarUrl: avatar('DRV-514'),
    completedToday: 3,
    reviews: reviewsFor('DRV-514', [
      {
        customerName: 'Ananya S.',
        customerAvatar: avatar('c-ananya'),
        rating: 4,
        text: sampleReviewTexts[3],
        deliveryDate: '2026-05-02',
        orderId: 'O-99150',
      },
    ]),
    deliveries: deliveriesTemplate('514'),
    weeklyEarningsSeries: weekSeries(10),
    monthlyEarningsSeries: monthSeries(11),
    deliveryGrowthSeries: growthSeries(12),
  },
  {
    id: 'DRV-515',
    name: 'Fatima Noor',
    email: 'fatima.noor@bd.test',
    phone: '+880 1912 667788',
    country: 'Bangladesh',
    vehicleType: 'Motorcycle',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'delivering',
    rating: 4.85,
    ratingCount: 402,
    completedOrders: 2210,
    cancelledOrders: 36,
    totalEarnings: 55440.25,
    weeklyEarnings: 1320.0,
    joinDate: '2024-01-08',
    avgDeliveryMinutes: 23,
    avatarUrl: avatar('DRV-515'),
    completedToday: 12,
    reviews: reviewsFor('DRV-515', [
      {
        customerName: 'Imran S.',
        customerAvatar: avatar('c-imran'),
        rating: 5,
        text: sampleReviewTexts[0],
        deliveryDate: '2026-05-03',
        orderId: 'O-99377',
      },
    ]),
    deliveries: deliveriesTemplate('515'),
    weeklyEarningsSeries: weekSeries(11),
    monthlyEarningsSeries: monthSeries(10),
    deliveryGrowthSeries: growthSeries(13),
  },
  {
    id: 'DRV-516',
    name: 'George Papadopoulos',
    email: 'g.pap@gr.test',
    phone: '+30 694 221 8890',
    country: 'Greece',
    vehicleType: 'Bicycle',
    accountStatus: 'suspended',
    verified: true,
    liveStatus: 'offline',
    rating: 4.0,
    ratingCount: 56,
    completedOrders: 310,
    cancelledOrders: 22,
    totalEarnings: 7800.0,
    weeklyEarnings: 0,
    joinDate: '2025-06-30',
    avgDeliveryMinutes: 29,
    avatarUrl: avatar('DRV-516'),
    completedToday: 0,
    reviews: reviewsFor('DRV-516', [
      {
        customerName: 'Maria K.',
        customerAvatar: avatar('c-maria'),
        rating: 3,
        text: 'Acceptable.',
        deliveryDate: '2026-04-25',
        orderId: 'O-98550',
      },
    ]),
    deliveries: deliveriesTemplate('516'),
    weeklyEarningsSeries: weekSeries(2),
    monthlyEarningsSeries: monthSeries(2),
    deliveryGrowthSeries: growthSeries(5),
  },
  {
    id: 'DRV-517',
    name: 'Chloe Martin',
    email: 'chloe.martin@fr.test',
    phone: '+33 6 12 34 56 78',
    country: 'France',
    vehicleType: 'Bicycle',
    accountStatus: 'active',
    verified: true,
    liveStatus: 'idle',
    rating: 4.55,
    ratingCount: 178,
    completedOrders: 920,
    cancelledOrders: 14,
    totalEarnings: 24660.0,
    weeklyEarnings: 540.75,
    joinDate: '2024-08-19',
    avgDeliveryMinutes: 20,
    avatarUrl: avatar('DRV-517'),
    completedToday: 4,
    reviews: reviewsFor('DRV-517', [
      {
        customerName: 'Jean D.',
        customerAvatar: avatar('c-jean'),
        rating: 5,
        text: sampleReviewTexts[2],
        deliveryDate: '2026-05-02',
        orderId: 'O-99210',
      },
    ]),
    deliveries: deliveriesTemplate('517'),
    weeklyEarningsSeries: weekSeries(12),
    monthlyEarningsSeries: monthSeries(12),
    deliveryGrowthSeries: growthSeries(15),
  },
  {
    id: 'DRV-518',
    name: 'Diego Fernandez',
    email: 'diego.f@mx.test',
    phone: '+52 55 1234 8899',
    country: 'Mexico',
    vehicleType: 'Motorcycle',
    accountStatus: 'active',
    verified: false,
    liveStatus: 'online',
    rating: 4.1,
    ratingCount: 34,
    completedOrders: 120,
    cancelledOrders: 6,
    totalEarnings: 2880.5,
    weeklyEarnings: 198.25,
    joinDate: '2026-03-28',
    avgDeliveryMinutes: 27,
    avatarUrl: avatar('DRV-518'),
    completedToday: 2,
    reviews: reviewsFor('DRV-518', [
      {
        customerName: 'Carla M.',
        customerAvatar: avatar('c-carla'),
        rating: 4,
        text: sampleReviewTexts[1],
        deliveryDate: '2026-05-01',
        orderId: 'O-99001',
      },
    ]),
    deliveries: deliveriesTemplate('518'),
    weeklyEarningsSeries: weekSeries(13),
    monthlyEarningsSeries: monthSeries(3),
    deliveryGrowthSeries: growthSeries(16),
  },
]

export function computeOverviewStats(drivers: DeliveryDriver[]) {
  const activeDrivers = drivers.filter((d) => d.accountStatus === 'active').length
  const pendingApprovals = drivers.filter((d) => d.accountStatus === 'pending').length
  const onlineDrivers = drivers.filter(
    (d) => d.accountStatus === 'active' && (d.liveStatus === 'online' || d.liveStatus === 'delivering'),
  ).length
  const completedDeliveriesToday = drivers.reduce((s, d) => s + d.completedToday, 0)
  const totalDriverEarnings = drivers.reduce((s, d) => s + d.totalEarnings, 0)
  return {
    totalDrivers: drivers.length,
    activeDrivers,
    pendingApprovals,
    onlineDrivers,
    completedDeliveriesToday,
    totalDriverEarnings,
  }
}
